CREATE TABLE SYS_USERS
(
    USERID      VARCHAR(64) COMMENT '用户代码' NOT NULL
                UNIQUE PRIMARY KEY,
    ORGID       VARCHAR(20) COMMENT '机构编号' NOT NULL,
    USERNAME    VARCHAR(10) COMMENT '用户名称',
    USERCLASS   VARCHAR(4) COMMENT '用户类别 01前台 02中台 03后台',
    SEX         CHAR COMMENT '用户性别',
    IDCARD      VARCHAR(20) COMMENT '身份证号',
    PASSWOED    VARCHAR(64) COMMENT '用户密码',
    EMAIL       VARCHAR(50) COMMENT '用户邮箱',
    STATUS      INT COMMENT '启用状态 1启用 0禁用',
    ADMINFLAG   CHAR COMMENT '管理员标识 Y是 N不是',
    TELNO       VARCHAR(20) COMMENT '联系方式',
    CREATDATE   TIMESTAMP COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP,
    LSTMNTDATE  TIMESTAMP COMMENT '更新时间',
    LSTMNUSER   VARCHAR(64) COMMENT '更新用户',
    EFFECTFLAG  CHAR COMMENT '有效标识',
    FIELD1      VARCHAR(100) COMMENT '预留字段1',
    FIELD2      VARCHAR(100) COMMENT '预留字段2',
    FIELD3      VARCHAR(100) COMMENT '预留字段3'
)
COMMENT = '用户信息表';