from django.db import models


# Create your models here.
class SysUsers(models.Model):
    USERID = models.CharField(help_text='用户代码', max_length=64, primary_key=True, unique=True)
    ORGID = models.CharField(help_text='机构编号', max_length=20)
    USERNAME = models.CharField(help_text='用户名称', max_length=10)
    USERCLASS = models.CharField(help_text='用户类别 01前台 02中台 03后台 04管理员', max_length=4)
    SEX = models.CharField(help_text='用户性别', max_length=1, blank=True, null=True)
    IDCARD = models.CharField(help_text='身份证号', max_length=20)
    PASSWOED = models.CharField(help_text='用户密码', max_length=64)
    EMAIL = models.CharField(help_text='用户邮箱', max_length=50, blank=True, null=True)
    STATUS = models.CharField(help_text='启用状态 1启用 0禁用', max_length=1)
    ADMINFLAG = models.CharField(help_text='管理员标识 Y是 N不是', max_length=1)
    TELNO = models.CharField(help_text='联系方式', max_length=20, blank=True, null=True)
    CREATDATE = models.DateTimeField(help_text='创建时间', blank=True, null=True)
    LSTMNDATE = models.DateTimeField(help_text='更新时间', blank=True, null=True)
    LSTMNUSER = models.CharField(help_text='更新人员', max_length=64, blank=True, null=True)
    EFFECTFLAG = models.CharField(help_text='有效标识', max_length=1)

    class Meta:
        db_table = "SYS_USERS"
        verbose_name = '用户信息表'


class SecInfo(models.Model):
    SEQNO = models.AutoField(help_text="序号", primary_key=True)
    SECID = models.CharField(max_length=20, )
    SECNAME = models.CharField(max_length=100)
    PRODUCT = models.CharField(max_length=6)
    PRODTYPE = models.CharField(max_length=2)
    ACCTNGTYPE = models.CharField(max_length=10)
    ISSUESUBJECT1 = models.CharField(max_length=40)
    ISSUESUBJECT2 = models.CharField(max_length=6)
    INTCALRULE = models.CharField(max_length=10)
    VDATE = models.DateTimeField()
    MDATE = models.DateTimeField()
    TERM = models.IntegerField()
    TERMUNIT = models.IntegerField()
    ISSUEPRICE = models.DecimalField(max_digits=6, decimal_places=6, default=100)
    DENOM = models.IntegerField(default=100)
    CCY = models.CharField(max_length=8, default="CNY")
    PARVALUE = models.DecimalField(max_digits=26, decimal_places=4, default=100)
    RETURNTYPE = models.CharField(max_length=10)
    SECSUBTYPE = models.CharField(max_length=10)
    SETTCCY = models.CharField(max_length=50)
    BASIS = models.CharField(max_length=6)
    ADJUSTRULE = models.CharField(max_length=10)
    PAYCYCLE = models.CharField(max_length=3)
    SCHECALRULE = models.CharField(max_length=2)
    FIRSTPAYDATE = models.CharField(max_length=12)
    INTTYPE = models.CharField(max_length=2)
    PAPERIP = models.DecimalField(max_digits=6, decimal_places=6)
    RATECODE = models.CharField(max_length=20)
    FACTOR = models.DecimalField(max_digits=6, decimal_places=6)
    SPREADRATE = models.DecimalField(max_digits=6, decimal_places=6)
    TOPRATEFLAG = models.CharField(max_length=1)
    TOPRATE = models.DecimalField(max_digits=6, decimal_places=6)
    BOTTOMRATEFLAG = models.CharField(max_length=1)
    BOTTOMRATE = models.DecimalField(max_digits=6, decimal_places=6)
    RATEVALUETYPE = models.CharField(max_length=1, null=True, blank=True)
    RATEVALUEPERIOD = models.CharField(max_length=1, null=True, blank=True)
    RATEVALUEDAYS = models.IntegerField(null=True, blank=True)
    INTPAYRULE = models.CharField(max_length=1, null=True, blank=True)
    ISSUEAMT = models.DecimalField(max_digits=26, decimal_places=4)
    EXERCISEFLAG = models.CharField(max_length=1)
    VIRTUALFLAG = models.CharField(max_length=1, null=True, blank=True)
    CONVERTFLAG = models.CharField(max_length=1, null=True, blank=True)
    PRINBACKFLAG = models.CharField(max_length=1, null=True, blank=True)
    CREATEDATE = models.DateTimeField(null=True, blank=True)
    EFFECTFLAG = models.CharField(max_length=1)
    LSTMNTDATE = models.DateTimeField()
    LSTMNTUSER = models.CharField(max_length=64)
    FULLNAME = models.CharField(max_length=150)
    SRCSECID = models.CharField(max_length=20, null=True, blank=True)
    RETURNSUBTYPE = models.CharField(max_length=10, null=True, blank=True)
    RTRANUSER = models.CharField(max_length=64)
    RTRANNAME = models.CharField(max_length=20)
    ORGID = models.CharField(max_length=20)
    ORGNAME = models.CharField(max_length=100)
    SECMARKETID = models.CharField(max_length=40)

    class Meta:
        db_table = 'TGT_SECINFO'
        verbose_name = "债券信息表"
